# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tobuyitem",
            index=models.Index(
                fields=["makerspace", "kind", "-created_at"],
                name="proc_tobuy_scope_created_idx",
            ),
        ),
    ]