# Generated by Django 5.1.15 on 2026-06-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryproduct_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='tracking_mode',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('individual', 'Individual')], default='quantity', max_length=20),
        ),
    ]
