# Generated by Django 5.1.15 on 2026-06-10 15:06

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_box_parent'),
        ('inventory', '0003_remove_inventoryproduct_image_url_and_more'),
        ('makerspaces', '0003_alter_makerspacemembership_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryproduct',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('available_quantity'), '+', models.F('reserved_quantity')), '+', models.F('issued_quantity')), '+', models.F('damaged_quantity')), '+', models.F('lost_quantity')))), name='qty_sum_within_total'),
        ),
    ]
