# Generated by Django 5.1.15 on 2026-06-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_qrcode_qrscanevent_qrcode_uniq_active_qr_per_target'),
        ('inventory', '0004_inventoryproduct_qty_sum_within_total'),
        ('makerspaces', '0005_alter_makerspace_public_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('retired', 'Retired'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='boxes.box')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='makerspaces.makerspace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='inventory.inventoryproduct')),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'status'], name='inventory_i_makersp_61239a_idx')],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'asset_tag'), name='uniq_asset_tag_per_makerspace')],
            },
        ),
    ]
