# Generated by Django 5.1.15 on 2026-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventoryproduct_qty_sum_within_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
