# Generated by Django 5.1.15 on 2026-06-27 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0009_inventoryproduct_image_key'),
        ('makerspaces', '0023_makerspace_geolocation'),
        ('printing', '0015_printrequest_contact_email_lower_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('warranty_expires_on', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='inventory.inventoryasset')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='makerspaces.makerspace')),
                ('printer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='printing.printprinter')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=300, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warranty.warranty')),
            ],
        ),
        migrations.AddConstraint(
            model_name='warranty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('printer__isnull', True)), models.Q(('asset__isnull', True), ('printer__isnull', False)), _connector='OR'), name='warranty_exactly_one_host'),
        ),
    ]
