from django.urls import path

from apps.hardware_requests import cron_views, views

app_name = "hardware_requests"

urlpatterns = [
    path(
        "internal/cron/return-reminders",
        cron_views.ReturnReminderCronView.as_view(),
        name="cron-return-reminders",
    ),
    path(
        "public/<slug:makerspace_slug>/checkin/verify",
        views.CheckinVerifyView.as_view(),
        name="checkin-verify",
    ),
    path(
        "public/<slug:makerspace_slug>/requests",
        views.RequestSubmitView.as_view(),
        name="request-submit",
    ),
    path(
        "public/<slug:makerspace_slug>/requests/status",
        views.RequestLookupView.as_view(),
        name="request-lookup",
    ),
    path(
        "public/<slug:makerspace_slug>/tools/evidence-url",
        views.PublicToolEvidenceUploadUrlView.as_view(),
        name="public-tool-evidence-url",
    ),
    path(
        "public/<slug:makerspace_slug>/tools/checkout",
        views.PublicToolCheckoutView.as_view(),
        name="public-tool-checkout",
    ),
    path(
        "public/<slug:makerspace_slug>/tools/return",
        views.PublicToolReturnView.as_view(),
        name="public-tool-return",
    ),
    path(
        "public/requests/<uuid:public_token>/status",
        views.RequestStatusView.as_view(),
        name="request-status",
    ),
    path(
        "admin/makerspace/<int:makerspace_id>/pending-requests",
        views.PendingRequestsView.as_view(),
        name="pending-requests",
    ),
    path(
        "admin/makerspace/<int:makerspace_id>/accepted-requests",
        views.AcceptedRequestsView.as_view(),
        name="accepted-requests",
    ),
    path(
        "admin/makerspace/<int:makerspace_id>/active-loans",
        views.ActiveLoansView.as_view(),
        name="active-loans",
    ),
    path(
        "admin/makerspace/<int:makerspace_id>/request-history",
        views.RequestHistoryView.as_view(),
        name="request-history",
    ),
    path(
        "admin/makerspace/<int:makerspace_id>/direct-loans",
        views.DirectLoanListCreateView.as_view(),
        name="direct-loans",
    ),
    path(
        "admin/makerspace/<int:makerspace_id>/checkin/verify",
        views.StaffCheckinVerifyView.as_view(),
        name="staff-checkin-verify",
    ),
    path(
        "admin/direct-loans/<int:pk>/return",
        views.DirectLoanReturnView.as_view(),
        name="direct-loan-return",
    ),
    path(
        "admin/requests/<int:pk>/accept",
        views.AcceptRequestView.as_view(),
        name="request-accept",
    ),
    path(
        "admin/requests/<int:pk>/reject",
        views.RejectRequestView.as_view(),
        name="request-reject",
    ),
    path(
        "admin/requests/<int:pk>/assign-box",
        views.AssignBoxView.as_view(),
        name="request-assign-box",
    ),
    path(
        "admin/requests/<int:pk>/issue",
        views.IssueRequestView.as_view(),
        name="request-issue",
    ),
    path(
        "admin/requests/<int:pk>/return-due",
        views.SetReturnDueView.as_view(),
        name="request-return-due",
    ),
    path(
        "admin/requests/<int:pk>/return",
        views.ReturnRequestView.as_view(),
        name="request-return",
    ),
    path(
        "guest-admin/makerspace/<int:makerspace_id>/active-loans",
        views.ActiveLoansView.as_view(),
        name="guest-admin-active-loans",
    ),
    path(
        "guest-admin/requests/<int:pk>/return",
        views.ReturnRequestView.as_view(),
        name="guest-admin-request-return",
    ),
]
