# Generated by Django 5.1.15 on 2026-06-10 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_remove_inventoryproduct_image_url_and_more'),
        ('makerspaces', '0003_alter_makerspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_username', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('issued', 'Issued'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned'), ('closed_with_issue', 'Closed with Issue')], db_index=True, default='pending_approval', max_length=32)),
                ('requested_for', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_requests', to='makerspaces.makerspace')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hardware_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField()),
                ('accepted_quantity', models.PositiveIntegerField(default=0)),
                ('issued_quantity', models.PositiveIntegerField(default=0)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('missing_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventoryproduct')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hardware_requests.hardwarerequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='hardwarerequest',
            index=models.Index(fields=['makerspace', 'status'], name='hardware_re_makersp_a4c2d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='hardwarerequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gte', 1)), name='req_item_qty_positive'),
        ),
    ]
