# Generated by Django 5.1.15 on 2026-06-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_boxscan'),
        ('evidence', '0002_evidencephoto_immutable_triggers'),
        ('hardware_requests', '0001_initial'),
        ('makerspaces', '0003_alter_makerspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerequest',
            name='assigned_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boxes.box'),
        ),
        migrations.AddField(
            model_name='hardwarerequest',
            name='issue_evidence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_request', to='evidence.evidencephoto'),
        ),
        migrations.AddField(
            model_name='hardwarerequest',
            name='issue_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hardwarerequest',
            name='issued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hardwarerequest',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='hardwarerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['issued', 'partially_returned'])), fields=('assigned_box',), name='uniq_active_loan_per_box'),
        ),
    ]
