# Generated by Django 5.1.15 on 2026-06-11 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_boxscan_immutable_triggers'),
        ('evidence', '0002_evidencephoto_immutable_triggers'),
        ('hardware_requests', '0002_hardwarerequest_assigned_box_and_more'),
        ('makerspaces', '0003_alter_makerspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterAccountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('damaged', 'Damaged'), ('missing', 'Missing')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='evidence.evidencephoto')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='makerspaces.makerspace')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardware_requests.hardwarerequest')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardware_requests.hardwarerequestitem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountability_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boxes.box')),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_event', to='evidence.evidencephoto')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='makerspaces.makerspace')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hardware_requests.hardwarerequest')),
            ],
        ),
    ]
