# Generated by Django 5.1.15 on 2026-06-13 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_requests', '0010_hardwarerequest_return_due_at_and_more'),
        ('inventory', '0006_public_self_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRequestItemAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('lost', 'Lost')], db_index=True, default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventoryasset')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='hardware_requests.hardwarerequestitem')),
                ('return_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hardware_requests.returnevent')),
            ],
            options={
                'indexes': [models.Index(fields=['request_item', 'outcome'], name='hardware_re_request_084ae5_idx')],
                'constraints': [models.UniqueConstraint(fields=('request_item', 'asset'), name='uniq_request_item_asset')],
            },
        ),
    ]
