# Generated by Django 5.1.15 on 2026-06-06 21:31

import apps.boxes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0002_makerspacemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.boxes.models.generate_box_code, editable=False, max_length=32, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='makerspaces.makerspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'label'), name='uniq_box_label_per_makerspace')],
            },
        ),
    ]
