# Generated by Django 5.1.15 on 2026-06-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_box_parent'),
        ('hardware_requests', '0001_initial'),
        ('makerspaces', '0003_alter_makerspacemembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('issue', 'Issue'), ('return', 'Return')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='boxes.box')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_scans', to='makerspaces.makerspace')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hardware_requests.hardwarerequest')),
            ],
        ),
    ]
