# Generated by Django 5.1.15 on 2026-06-11 07:17

import apps.boxes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_boxscan_immutable_triggers'),
        ('hardware_requests', '0004_return_records_immutable_triggers'),
        ('makerspaces', '0005_alter_makerspace_public_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(default=apps.boxes.models.generate_box_code, max_length=64, unique=True)),
                ('target_type', models.CharField(choices=[('box', 'Box'), ('product', 'Product'), ('asset', 'Asset')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='makerspaces.makerspace')),
            ],
        ),
        migrations.CreateModel(
            name='QrScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('issue', 'Issue'), ('return', 'Return'), ('inventory_check', 'Inventory Check'), ('reassignment', 'Reassignment')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_scan_events', to='makerspaces.makerspace')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='boxes.qrcode')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hardware_requests.hardwarerequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='qrcode',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('makerspace', 'target_type', 'target_id'), name='uniq_active_qr_per_target'),
        ),
    ]
