# Generated by Django 5.1.15 on 2026-06-14 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _fill_public_tokens(apps, schema_editor):
    PrintRequest = apps.get_model("printing", "PrintRequest")
    for request in PrintRequest.objects.filter(public_token__isnull=True):
        request.public_token = uuid.uuid4()
        request.save(update_fields=["public_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0012_makerspace_smtp_use_ssl'),
        ('printing', '0003_printrequest_estimated_filament_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='project_brief',
            field=models.TextField(blank=True),
        ),
        # Add nullable WITHOUT a default first: a callable default on AddField is
        # evaluated once, so existing rows would all get the SAME uuid (then the unique
        # AlterField below would fail). Nullable-no-default leaves existing rows NULL for
        # the RunPython backfill to fill with per-row unique values.
        migrations.AddField(
            model_name='printrequest',
            name='public_token',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(_fill_public_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='printrequest',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='PrintRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stl', 'STL'), ('screenshot', 'Screenshot')], max_length=16)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('owner_checkin_user_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_request_files', to='makerspaces.makerspace')),
                ('print_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='printing.printrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
