# Generated by Django 5.1.15 on 2026-06-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0013_manualprintlog_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='printprinter',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
