# Generated by Codex on 2026-06-23

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0014_printprinter_image_key"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="printrequest",
            index=models.Index(
                Lower("contact_email"),
                name="printreq_contact_email_l_idx",
            ),
        ),
    ]