# Generated by Django 5.1.15 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0003_evidencephoto_purge_delete_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencephoto",
            name="content_type",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="evidencephoto",
            name="size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
