# Generated by Django 5.1.15 on 2026-06-06 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakerspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('guest_admin', 'Guest Admin')], default='admin', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='makerspaces.makerspace')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='makerspace_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'user'), name='uniq_makerspace_user')],
            },
        ),
    ]
