# Generated by Django 5.1.15 on 2026-06-11 07:17

import apps.makerspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0004_public_api_and_cors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerspace',
            name='public_api_key',
            field=models.CharField(default=apps.makerspaces.models.generate_publishable_key, editable=False, max_length=40),
        ),
    ]
