# Generated by Django 5.1.15 on 2026-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0018_alter_makerspace_frontend_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='cover_image_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='makerspace',
            name='logo_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
