# Generated by Django 5.1.15 on 2026-06-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0019_makerspace_cover_image_key_makerspace_logo_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='staff_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
