# Generated by Django 5.1.15 on 2026-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0021_makerspacemembership_receives_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='public_stats_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
