# Generated by Django 5.1.15 on 2026-06-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0023_makerspace_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='public_print_status_lookup_policy',
            field=models.CharField(choices=[('token_only', 'Token only'), ('email_unverified', 'Email unverified'), ('checkin_verified', 'Check-In verified')], default='email_unverified', max_length=32),
        ),
    ]
