# Generated by Django 5.1.15 on 2026-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('external_checkin_user_id', ''), _negated=True), fields=('external_checkin_user_id',), name='uniq_external_checkin_user_id'),
        ),
    ]
