# Generated by Django 5.1.15 on 2026-06-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_migrate_hardware_templates'),
        ('makerspaces', '0023_makerspace_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('stream', models.CharField(blank=True, max_length=32)),
                ('event', models.CharField(blank=True, max_length=64)),
                ('audience', models.CharField(blank=True, max_length=16)),
                ('connection_kind', models.CharField(default='makerspace', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('makerspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['makerspace', '-created_at'], name='integration_makersp_dd2a84_idx'), models.Index(fields=['status'], name='integration_status_96d8d0_idx')],
            },
        ),
    ]
