# Generated by Codex on 2026-06-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0004_emaillog"),
        ("makerspaces", "0023_makerspace_geolocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationMute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=32)),
                ("stream", models.CharField(max_length=16)),
                ("event", models.CharField(max_length=64)),
                ("audience", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "makerspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_mutes",
                        to="makerspaces.makerspace",
                    ),
                ),
            ],
            options={
                "ordering": ["makerspace__name", "stream", "event"],
                "indexes": [
                    models.Index(
                        fields=["makerspace", "stream", "audience"],
                        name="integration_makers_2fcfc9_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="emailnotificationmute",
            constraint=models.UniqueConstraint(
                fields=("makerspace", "target", "stream", "event"),
                name="uniq_email_mute_row",
            ),
        ),
    ]
