# Generated by Django 5.1.15 on 2026-06-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_emailnotificationmute'),
        ('makerspaces', '0023_makerspace_geolocation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emaillog',
            name='integration_status_96d8d0_idx',
        ),
        migrations.RenameIndex(
            model_name='emailnotificationmute',
            new_name='integration_makersp_8c1f8c_idx',
            old_name='integration_makers_2fcfc9_idx',
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['makerspace', 'status', '-created_at'], name='integration_makersp_1d5eb0_idx'),
        ),
    ]
